Sdk
kib-sources/odc-android-app pull request #1
Opened 2021-07-21 11:57 UTC by aluzgin

2021-07-21 13:06 UTC, fktrcfylh1234567 requested changes

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/MainActivity.kt
> +            }
1) Лямбда в лямбде выглядит не очень. Лучше как-то вынести.
2) Такие вещи лучше делать во ViewModel. Сейчас пока можно без нее, но в конечно решении лучше переделать.

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +        Log.d("OpenDigitalCashA", alias)
Тэг лога лучше хранить в глобальной константе, чтобы он был задан в одном месте длял всего приложения.

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +        val publicKey: PublicKey = keyStore.getCertificate(simKeysAlias).publicKey
А тут точно нужно явно указывать тип?

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +        }
Зачем писать руками цикл, когда есть joinToString()?

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +    val pubKey: PublicKey
Зачем объявлять pubKey заранее?

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/ISO_4217_CODE.kt
> +            return "00" + this.code.toString()
Проще "00$code"

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Utils.kt
> +    }
Зачем циклом?
Есть же функции any, all, none/

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Wallet.kt
> +            throw java.lang.Exception("parentOtokSignature не указан!")
Убери java.lang

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Wallet.kt
> +            ) == false
if (!Crypto.verifySignature(...))

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankApi.kt
> +    suspend fun receiveBanknote(@Body ir: ReceiveRequest): ReceiveResponse
Жалательно, чтобы у аргементов было читабельные имена.

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +    private val url2 = "http://46.151.157.153:5000"
Кто первый, а кто второй?)
По названию не понятно, какой ip чей.

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +            editor.apply()
Не обязательно после добавления каждого поля вызывать apply()
Достаточно один раз в конце

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        if ((sokSignature == null) || (wid == null)) {
Лишние скобки.

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        if (rawBanknotes.isNotEmpty()) {
А разве для пустого массива этот код крашнется?

2021-07-21 13:06 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/Banknote.kt
> +    // TODO выгрузить из protobuf
protobuf?
Это еще зачем?

2021-08-19 07:09 UTC, fktrcfylh1234567 requested changes

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +        val sumView = view.findViewById<TextView>(R.id.sum)
findViewById в Котлине не нужен. Можно сразу по имени поля.
+ сделай нормальные имена для элементов экрана (button10 -> buttonReceive)

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +                    withContext(Dispatchers.Main) {
Чет сложно...
Зачем запускать в фоновом потом, а зетем сразу переключаться обратно?

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +                                        makeToast("Соединение установлено.")
Тосты для событий это конечно неплохо, но мне кажется не помещает отображать текущее состояние в отдельном поле.

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +                                makeToast("Соединение разорвано.")
Не понимаю, почему одно и тоже событие вознимает в двух разных местах?

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +        activity?.let {
requireActivity()

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +            for (b in result.values) {
Название переменной b вообще ни о чем не говорит.

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeFragment.kt
> +            var allAreGranted = true
result.values.all{ ... }

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/ExchangeViewModel.kt
> +    private val _sum = repo.getSum()
Нужно не поле в БД обсервить, а сделать локальный стейт и менять его при изменении баланса.

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/MainActivity.kt
> +        if (savedInstanceState == null) {
Я не уверен, что эта проверка точно нужна?

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +    }
Че за структурное программирование?)
if (PKCSObjectIdentifiers.rsaEncryption !== subjectPublicKeyInfo.algorithm.algorithm)
    throw Exception("loadPublicKey error")

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Crypto.kt
> +    }
И то что сравнение по ссылке, это так и должно быть?

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        Room.databaseBuilder(context, BlockchainDatabase::class.java, "blockchain").build()
Для Room обычно просто фабрику делают. Так удобнее.)

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        }
Мне кажется запускать этот процесс прям при создании не особо имеет смысл.

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +//Клиент А -> Клиент Б
Советую запомнить одно просто правило:
если у тебя возникает жалание сделать коммент для разделения кода по смыслу, то явной признак того, пора созавать новый класс.)

2021-08-19 07:09 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        if (container.blockchain != null) {
Опять структорное...
Если пришла муть, то продолжать выполнение кода уже смысла не много.
if (container.blockchain == null)
   return

2021-08-19 19:19 UTC, aluzgin commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        if (container.blockchain != null) {
В зависимости от того, что именно содержится в пришедшем PayloadContainer, выполняются те или иные действия (всего 3 варианта). Проверка выполняется определением наличия или отсутствия поля в PayloadContainer.
Можно в payload передавать переменную, в которой записан тип пересылаемой информации. Тогда будет проще понять код, но прийдётся пересылать переменную, без которой вполне можно обойтись.

2021-08-19 19:34 UTC, aluzgin commented on app/src/main/java/npo/kib/odc_demo/core/Utils.kt
> +    }
Здесь нужно итерироваться одновременно по обоим хэшам. Как это сделать через all не знаю

2021-08-19 19:38 UTC, aluzgin commented on app/src/main/java/npo/kib/odc_demo/data/BankRepository.kt
> +        if (rawBanknotes.isNotEmpty()) {
Не крашнется. Можно и убрать проверку.

2021-08-20 01:48 UTC, fktrcfylh1234567 commented on app/src/main/java/npo/kib/odc_demo/core/Utils.kt
> +    }
`    fun checkHashes(hash1: ByteArray, hash2: ByteArray): Boolean {
        if (hash1.count() != hash2.count()) {
            return false
        }

        return hash1.zip(hash2).all { (first, second) -> first == second }
    }
`

2021-08-25 12:00 UTC, fktrcfylh1234567 approved these changes, later dismissed

2021-09-07 04:17 UTC, fktrcfylh1234567 approved these changes

2021-09-07 04:17 UTC, merged